package com.zrich.model;

public class User {

  /**
   * This field was generated by MyBatis Generator. This field corresponds to the database column public.user.id
   * @mbggenerated  Sun Dec 24 17:17:15 CST 2017
   */
  private Integer id;
  /**
   * This field was generated by MyBatis Generator. This field corresponds to the database column public.user.name
   * @mbggenerated  Sun Dec 24 17:17:15 CST 2017
   */
  private String name;
  /**
   * This field was generated by MyBatis Generator. This field corresponds to the database column public.user.gender
   * @mbggenerated  Sun Dec 24 17:17:15 CST 2017
   */
  private String gender;
  /**
   * This field was generated by MyBatis Generator. This field corresponds to the database column public.user.email
   * @mbggenerated  Sun Dec 24 17:17:15 CST 2017
   */
  private String email;
  /**
   * This field was generated by MyBatis Generator. This field corresponds to the database column public.user.address
   * @mbggenerated  Sun Dec 24 17:17:15 CST 2017
   */
  private String address;

  /**
   * This method was generated by MyBatis Generator. This method returns the value of the database column public.user.id
   * @return  the value of public.user.id
   * @mbggenerated  Sun Dec 24 17:17:15 CST 2017
   */
  public Integer getId() {
    return id;
  }

  /**
   * This method was generated by MyBatis Generator. This method sets the value of the database column public.user.id
   * @param id  the value for public.user.id
   * @mbggenerated  Sun Dec 24 17:17:15 CST 2017
   */
  public void setId(Integer id) {
    this.id = id;
  }

  /**
   * This method was generated by MyBatis Generator. This method returns the value of the database column public.user.name
   * @return  the value of public.user.name
   * @mbggenerated  Sun Dec 24 17:17:15 CST 2017
   */
  public String getName() {
    return name;
  }

  /**
   * This method was generated by MyBatis Generator. This method sets the value of the database column public.user.name
   * @param name  the value for public.user.name
   * @mbggenerated  Sun Dec 24 17:17:15 CST 2017
   */
  public void setName(String name) {
    this.name = name;
  }

  /**
   * This method was generated by MyBatis Generator. This method returns the value of the database column public.user.gender
   * @return  the value of public.user.gender
   * @mbggenerated  Sun Dec 24 17:17:15 CST 2017
   */
  public String getGender() {
    return gender;
  }

  /**
   * This method was generated by MyBatis Generator. This method sets the value of the database column public.user.gender
   * @param gender  the value for public.user.gender
   * @mbggenerated  Sun Dec 24 17:17:15 CST 2017
   */
  public void setGender(String gender) {
    this.gender = gender;
  }

  /**
   * This method was generated by MyBatis Generator. This method returns the value of the database column public.user.email
   * @return  the value of public.user.email
   * @mbggenerated  Sun Dec 24 17:17:15 CST 2017
   */
  public String getEmail() {
    return email;
  }

  /**
   * This method was generated by MyBatis Generator. This method sets the value of the database column public.user.email
   * @param email  the value for public.user.email
   * @mbggenerated  Sun Dec 24 17:17:15 CST 2017
   */
  public void setEmail(String email) {
    this.email = email;
  }

  /**
   * This method was generated by MyBatis Generator. This method returns the value of the database column public.user.address
   * @return  the value of public.user.address
   * @mbggenerated  Sun Dec 24 17:17:15 CST 2017
   */
  public String getAddress() {
    return address;
  }

  /**
   * This method was generated by MyBatis Generator. This method sets the value of the database column public.user.address
   * @param address  the value for public.user.address
   * @mbggenerated  Sun Dec 24 17:17:15 CST 2017
   */
  public void setAddress(String address) {
    this.address = address;
  }
}